baseURL = "https://wellarchitecture.cloud"
languageCode = "en-us"
title = "Well Architecture Cloud - AWS Well Architected Framework journey and experiences"
theme = "mini"
defaultContentLanguage = "en"
#themesDir = "../../"
hasCJKLanguage = true
paginate = 3
googleAnalytics = "G-JKZ8MM61PD"
disqusShortname = "your-disqus-shortname"

# Disable category and tags - https://codingnconcepts.com/hugo/disable-taxonomy-pages-hugo/
disableKinds = ["taxonomy", "term"]

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

#[social]
#github = "well-architected"
#twitter = "well-architected"
#stackoverflow = "well-architected"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[params]
author = "Well Architected Cloud"
bio = "A journey for AWS Well Architected Framework"
description = "The AWS Well Architected Framework helps organizations move to the cloud in a well-architected way. In this blog, we'll share our experiences with the framework and provide tips on how to get the most out of it."
enableRSS = false
enableComments = false
enableRobotsTXT = false
enableGoogleAnalytics = true
showToc = false
showPowerBy = false
math = false
hiddenPostSummaryInHomePage = false
copyright = ""
about = false
#[[params.links]]
#name = "Project"
#path = "/project"
